source :rubygems

# Project requirements
gem 'rake'
gem 'rack-flash'
gem 'thin' # or mongrel

# Component requirements
gem 'haml'

# Test requirements

# Padrino
gem 'padrino', '0.9.29'

gem 'sinatra-simple-navigation', "3.3.2", :require => 'sinatra/simple-navigation'
gem 'i18n'
